[package]
name = "usb_driver_linux"
version = "0.1.0"
edition = "2021"

[dependencies]
continuity_common = { path = "../../lib/common" }
tokio = { version = "1.16.1", features = ["full"] }

[dependencies.usboip_driver_linux]
git = "https://github.com/continuity-kvm/usboip"
branch = "main"

[dependencies.usboip_client]
git = "https://github.com/continuity-kvm/usboip"
branch = "main"
